apiVersion: apps/v1

kind: Deployment

metadata:
  name: doc-deployment
  labels:
    app: doc

spec:
  replicas: 3
  selector:
    matchLabels:
      app: doc
  template:
    metadata:
      labels:
        app: doc
    spec:
      containers:
      - name: doc
        image: rahulshri0703/doc
        ports:
        - containerPort: 5000
